# Generated by Django 3.2.18 on 2023-04-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=80)),
                ('food_ingredients', models.CharField(max_length=100)),
                ('food_allergy', models.IntegerField(default=0)),
                ('food_price', models.IntegerField()),
                ('food_picture', models.ImageField(upload_to='')),
                ('food_state', models.BooleanField(default=True)),
            ],
        ),
    ]
