# Generated by Django 3.2.18 on 2023-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_allergy',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Milk'), (2, 'Egg'), (3, 'Peanuts'), (4, 'Flour')], default=0),
        ),
    ]
