# Generated by Django 3.2.18 on 2023-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_food_food_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_name', models.CharField(max_length=25)),
                ('food_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_ingredients',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_allergy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
