# Generated by Django 3.2.18 on 2023-05-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table_id',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
