# Generated by Django 3.2.18 on 2023-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20230502_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='leiras',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
