# Generated by Django 3.2.19 on 2023-05-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_food_leiras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='table_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
            preserve_default=False,
        ),
    ]
