# Generated by Django 3.2.18 on 2023-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20230518_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AddField(
            model_name='table',
            name='restaurant_name',
            field=models.CharField(default='djantaurant', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
