# Generated by Django 3.2.18 on 2023-05-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20230518_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='restaurant_name',
        ),
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, default='djantaurant', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
