# Generated by Django 3.2.18 on 2023-05-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20230518_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='id',
            field=models.BigAutoField(auto_created=True, default='djantaurant', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='restaurant_name',
            field=models.CharField(max_length=30),
        ),
    ]
