# Generated by Django 3.2.18 on 2023-05-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20230524_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
