# Generated by Django 3.2.18 on 2023-05-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
